export * from '../../protocol/src/command-analysis.js';
export type { ParseShellResult } from './shells/index.js';

export const ANALYSIS_BOUNDS = {
  MAX_SCRIPT_BYTES: 64 * 1024,
  MAX_NODES: 256,
  MAX_NESTED_DEPTH: 4,
  MAX_CWD_ALTERNATIVES: 32,
  PARSE_BUDGET_MS: 1500,
} as const;

export const REASON_CODES = {
  PARSE_INVALID: 'PARSE_INVALID',
  UNSUPPORTED_SYNTAX: 'UNSUPPORTED_SYNTAX',
  DYNAMIC_SCOPE: 'DYNAMIC_SCOPE',
  OUTSIDE_WORKSPACE: 'OUTSIDE_WORKSPACE',
  TOOL_NOT_FOUND: 'TOOL_NOT_FOUND',
  EXECUTABLE_CHANGED: 'EXECUTABLE_CHANGED',
  SCRIPT_CHANGED: 'SCRIPT_CHANGED',
  UNKNOWN_OPTION: 'UNKNOWN_OPTION',
  CONTEXT_CHANGED: 'CONTEXT_CHANGED',
  ANALYSIS_LIMIT: 'ANALYSIS_LIMIT',
} as const;

export type ReasonCode = (typeof REASON_CODES)[keyof typeof REASON_CODES];
